update

diff --git a/.github/workflows/SpatGris-builds.yml b/.github/workflows/SpatGris-builds.yml
--- a/.github/workflows/SpatGris-builds.yml
+++ b/.github/workflows/SpatGris-builds.yml
@@ -56,8 +56,19 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v2
 
+      - name: Print current path
+        run: pwd
+
+      - name: List directory contents
+        run: ls -R
+
       - name: download JUCE
-        run: curl -L https://github.com/juce-framework/JUCE/releases/download/7.0.1/juce-7.0.1-mac.zip --output JUCE.zip
+        run: |
+          curl -L https://github.com/juce-framework/JUCE/releases/download/7.0.1/juce-7.0.1-mac.zip --output JUCE.zip
+          if [ ! -f JUCE.zip ]; then
+            echo "JUCE.zip not found!"
+            exit 1
+          fi
 
       - name: unpack JUCE
         run: unzip JUCE.zip
@@ -85,6 +96,16 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v2
 
+      - name: Print current path
+        run: pwd
+
+      - name: List directory contents
+        run: ls -R
+
+      - name: Install Visual Studio Build Tools
+        run: |
+          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"
+
       - name: download JUCE
         run: curl -L https://github.com/juce-framework/JUCE/releases/download/7.0.1/juce-7.0.1-windows.zip --output JUCE.zip
 
@@ -100,7 +121,7 @@ jobs:
       - name: build
         run: |
           cd Builds/VisualStudio2022
-          msbuild SpatGRIS_App.vcxproj /p:Configuration=Release
+          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" SpatGRIS_App.vcxproj /p:Configuration=Release
 
       - name: Upload build artifacts
         uses: actions/upload-artifact@v4
